jsonp3(
{
 "status":"1",
 "message":"操作成功",
 "data":
 {
   "reg_no":"410500000000854",
   "credit_no":"-",
   "org_no":"172191923",
   "name":"安阳化学工业集团有限责任公司",
   "econ_kind":"其他有限责任公司",
   "scope":"化肥、化工原料生产（不含国家专项审批项目）。以下限分支机构经营：机械加工、工程建筑、交通运输、化工设计、商业、饮食服务；本集团其它成员企业的产品、技术、设备的生产经营和有关进出口业务。中餐、住宿。承包援越化肥厂工程及境内国际招标工程；上述境外工程所需的设备、材料出口；对外派遣实施上述境外工程所需的劳务人员。",
   "term_start":"1998-09-07",
   "term_end":"2018-08-20",
   "check_date":"2014-11-26",
   "belong_org":"安阳市工商行政管理局",
   "oper_name":"高恒",
   "start_date":"1998-09-07",
   "end_date":"",
   "status":"存续",
   "regist_capi":"159076.2786 万人民币",
   "province":"HN",
   "addresses":
     [
       {
        "name":"注册地址",
        "address":"安阳市龙安区彰武街",
        "postcode":""
       }
     ],
   "last_update_time":"2016-06-15",
   "logo_url":"",
   "partners":
     [
       {
         "seq_no":1,
         "eid":"",
         "stock_name":"安阳市人民政府国有资产监督管理委员会",
         "stock_type":"机关法人",
         "stock_percent":"",
         "should_capi_items":
           [
             {
               "shoud_capi":"",
               "should_capi_date":"",
               "invest_type":""
             }
           ],
         "real_capi_items":
           [
             {
               "real_capi":"",
               "real_capi_date":"",
               "invest_type":""
             }
           ]
       },
       {
         "seq_no":2,
         "eid":"1f6061ec-9ad4-4fe5-a6ef-a05c19fcb682",
         "stock_name":"河南能源化工集团有限公司",
         "stock_type":"法人股东",
         "stock_percent":"",
         "should_capi_items":
           [
             {
               "shoud_capi":"",
               "should_capi_date":"",
               "invest_type":""
             }
           ],
         "real_capi_items":
           [
             {
               "real_capi":"",
               "real_capi_date":"",
               "invest_type":""
             }
           ]
         },
         {
           "seq_no":3,"eid":"049b9608-ec08-4ee3-a110-3cea77bec7fc","stock_name":"安阳经济开发集团有限公司","stock_type":"法人股东","stock_percent":"","should_capi_items":[{"shoud_capi":"","should_capi_date":"","invest_type":""}],"real_capi_items":[{"real_capi":"","real_capi_date":"","invest_type":""}]}],"employees":[{"seq_no":1,"job_title":"董事长","name":"高恒","sex":"","cer_no":""},{"seq_no":2,"job_title":"监事","name":"申文平","sex":"","cer_no":""},{"seq_no":3,"job_title":"监事","name":"方征","sex":"","cer_no":""},{"seq_no":4,"job_title":"监事","name":"梁玉","sex":"","cer_no":""},{"seq_no":5,"job_title":"监事","name":"李勇","sex":"","cer_no":""},{"seq_no":6,"job_title":"监事","name":"张有铭","sex":"","cer_no":""},{"seq_no":7,"job_title":"监事","name":"杨海霞","sex":"","cer_no":""},{"seq_no":8,"job_title":"董事","name":"王玲","sex":"","cer_no":""},{"seq_no":9,"job_title":"副董事长","name":"李宝成","sex":"","cer_no":""},{"seq_no":10,"job_title":"监事","name":"刘志红","sex":"","cer_no":""},{"seq_no":11,"job_title":"董事","name":"郑惠国","sex":"","cer_no":""},{"seq_no":12,"job_title":"董事","name":"裴兴社","sex":"","cer_no":""},{"seq_no":13,"job_title":"董事","name":"李财","sex":"","cer_no":""},{"seq_no":14,"job_title":"董事","name":"谢俊生","sex":"","cer_no":""},{"seq_no":15,"job_title":"董事","name":"郭振远","sex":"","cer_no":""},{"seq_no":16,"job_title":"董事","name":"贾粮钢","sex":"","cer_no":""},{"seq_no":17,"job_title":"董事","name":"徐冰","sex":"","cer_no":""},{"seq_no":18,"job_title":"董事","name":"陈国平","sex":"","cer_no":""}],"branches":[{"eid":"","name":"安阳化学工业集团有限责任公司越南技改项目经理部"},{"eid":"","name":"安阳化学工业集团有限责任公司甲醇公司"}],"parameters":{}}});